#ifndef STRINGS
#define STRINGS



#include "MISC.h"
#include <stdarg.h>
#include <stdio.h>



#define EMPTY ""
#define STR_FAILURE 0
#define STR_SUCCESS 1
#define STR_WARNING 2




// [CONVERSION]
//


/**
 * BRIEF : TURNS A SINGLE LETTERED STRING INTO A CHAR
 *
 * NOTE  : IT WORKS BUT ONLY TAKING THE FIRST LETTER OF THE STRING, SO HAVING MULTIPLE CHAR STRINGS IS STILL ACCEPTED
 *
 * USAGE : printf("%c", STRING_TO_CHAR('A'));
*/
char STRING_TO_CHAR(const char* STRING);


/**
 * BRIEF : TURNS A STRING INTO A CHAR
 *
 * USAGE : STRING_TO_CHAR(STRING, 'A');
*/
void CHAR_TO_STRING(char* STRING, const char CHAR);


/**
 * BRIEF  : TURNS A STRING INTO A LIST, DIVDED BY SPACES
 *
 * NOTE 1 : RECOMMEND USING STRING_LIST_SETUP()
 *
 * NOTE 2 : BEFORE USING, THE char** STRING LIST SHOULD BE ALREADY ALLOCATED
 *
 * NOTE 2 : THE STRING IS AUTOMATICALLY TRIMMED
 *
 * USAGE  : STRING_TO_WORD_LIST(&STRING_LIST, "I LOVE C");
*/
void STRING_TO_WORD_LIST(char*** WORD_LIST, char* STRING);


/**
 * BRIEF  : TURNS A STRING LIST INTO A STRING
 *
 * RESULT : EACH ITEM OF THE STRING LIST WOULD BE PIECED TOGETHER, WITH A SPACED GAP
 *
 * NOTE   : REQUIRES USING STRING_LIST_SETUP(), AS THE LIST IS NULL TERMINATED
 *
 * USAGE  : WORD_LIST_TO_STRING(STRING_LIST, STRING);
*/
void WORD_LIST_TO_STRING(char** WORD_LIST, char* STRING);


/**
 * BRIEF  : TAKES A STRING THATS EXACTLY AN int FORMAT, AND EDITS INT TO IT
 *
 * NOTE 1 : IF THE STRING IS AN INVALID int FORMAT, IT RETURNS STR_FAILURE, OTHERWISE, STR_SUCCESS
 *
 * NOTE 2 : ANY int OVERFLOW WILL NOT BE HANDLED
 *
 * USAGE  : STRING_TO_INT("-12345", &INT);
*/
int STRING_TO_INT(const char* INT_STRING, int* INT);


/**
 * BRIEF  : TAKES A STRING THATS EXACTLY A long FORMAT, AND EDITS LONG TO IT
 *
 * NOTE 1 : IF THE STRING IS AN INVALID long FORMAT, IT RETURNS STR_FAILURE, OTHERWISE, STR_SUCCESS
 *
 * NOTE 2 : ANY long OVERFLOW WILL NOT BE HANDLED
 *
 * USAGE  : STRING_TO_LONG("-12345", &LONG);
*/
int STRING_TO_LONG(const char* INT_STRING, long* LONG);


/**
 * BRIEF  : TAKES A STRING THATS EXACTLY AN unsigned int FORMAT, AND EDITS INT TO IT
 *
 * NOTE 1 : IF THE STRING IS AN INVALID unsigned int FORMAT, IT RETURNS STR_FAILURE, OTHERWISE, STR_SUCCESS
 *
 * NOTE 2 : ANY unsigned int OVERFLOW WILL NOT BE HANDLED
 *
 * USAGE  : STRING_TO_UNSIGNED_INT("12345", &UNSIGNED_INT);
*/
int STRING_TO_UNSIGNED_INT(const char* STRING, unsigned int* UNSIGNED_INT);


/**
 * BRIEF  : TAKES A STRING THATS EXACTLY AN unsigned long FORMAT, AND EDITS UNSIGNED_LONG TO IT
 *
 * NOTE 1 : IF THE STRING IS AN INVALID unsigned long FORMAT, IT RETURNS STR_FAILURE, OTHERWISE, STR_SUCCESS
 *
 * NOTE 2 : ANY unsigned long OVERFLOW WILL NOT BE HANDLED
 *
 * USAGE  : STRING_TO_UNSIGNED_LONG("12345", &UNSIGNED_LONG);
*/
int STRING_TO_UNSIGNED_LONG(const char* STRING, unsigned long* UNSIGNED_LONG);


/**
 * BRIEF  : TAKES AN ANY INT TYPE FORMAT, AND EDITS STRING TO IT
 *
 * NOTE   : ANY INT OVERFLOW WILL NOT BE HANDLED
 *
 * USAGE  : INT_TO_STRING(INT_STRING, -12345);
*/
void INT_TO_STRING(char* STRING, long INT);


/**
 * BRIEF  : TAKES AN ANY UNSIGNED INT TYPE FORMAT, AND EDITS STRING TO IT
 *
 * NOTE   : ANY UNSIGNED INT OVERFLOW WILL NOT BE HANDLED
 *
 * USAGE  : INT_TO_STRING(UNSIGNED_INT_STRING, 12345);
*/
void UNSIGNED_INT_TO_STRING(char* STRING, unsigned long);


/**
 * BRIEF  : RETURNS THE UPPERCASE OF THE GIVEN LETTER
 *
 * RETURN : IF THE GIVEN CHAR IS IN LOWERCASE, RETURN THE UPPERCASE OF IT, OTHERWISE, RETURN THE ORIGINAL GIVEN CHAR
 *
 * NOTE   : ONLY WORKS FOR THE 26 LETTERS OF THE ENGLISH ALPHABET AND ASCII FORMAT
 *
 * USAGE  : char UPPERCASE_CHAR = CHAR_TO_UPPER('a');
*/
char CHAR_TO_UPPER(char CHAR);


/**
 * BRIEF  : RETURNS THE LOWERCASE OF THE GIVEN LETTER
 *
 * RETURN : IF THE GIVEN CHAR IS IN UPPERCASE, RETURN THE LOWERCASE OF IT, OTHERWISE, RETURN THE ORIGINAL GIVEN CHAR
 *
 * NOTE   : ONLY WORKS FOR THE 26 LETTERS OF THE ENGLISH ALPHABET AND ASCII FORMAT
 *
 * USAGE  : char LOWERCASE_CHAR = CHAR_TO_LOWER('A');
*/
char CHAR_TO_LOWER(char CHAR);


/**
 * BRIEF  : TAKES A STRING, EDITS ALL LOWERCASE LETTERS TO UPPERCASE
 *
 * NOTE 1 : THROUGH EACH CHAR IN THE STRING, IF THE CHAR IS IN LOWERCASE, EDIT IT TO UPPERCASE
 *
 * NOTE 2 : ONLY WORKS FOR THE 26 LETTERS OF THE ENGLISH ALPHABET AND ASCII FORMAT
 *
 * USAGE  : STRING_TO_UPPER(UPPERCASE_STRING);
*/
void STRING_TO_UPPER(char* STRING);


/**
 * BRIEF  : TAKES A STRING, EDITS ALL UPPERCASE LETTERS TO LOWERCASE
 *
 * NOTE 1 : THROUGH EACH CHAR IN THE STRING, IF THE CHAR IS IN LOWERCASE, EDIT IT TO UPPERCASE
 *
 * NOTE 2 : ONLY WORKS FOR THE 26 LETTERS OF THE ENGLISH ALPHABET AND ASCII FORMAT
 *
 * USAGE  : STRING_TO_LOWER(LOWERCASE_STRING);
*/
void STRING_TO_LOWER(char* STRING);


//
// [/CONVERISON]




// [EDIT]
//
void STRING_APPEND(char* STRING, const char* APPEND);

void STRING_APPEND_CHAR(char* STRING, const char CHAR);

void STRING_PREPEND(char* STRING, const char* PREPEND);

void STRING_PREPEND_CHAR(char* STRING, const char PREPEND);

int STRING_INSERT(char* STRING, const char* INSERT_STRING, const unsigned long INSERT_INDEX);

int STRING_INSERT_CHAR(char* STRING, const char INSERT_CHAR, const unsigned long INSERT_INDEX);

void STRING_FLIP(char* STRING);

int SUB_STRING_SELF(char* STRING, const unsigned long STARTING_INDEX, const unsigned long TO_TAKE);

int SUB_STRING(const char* BASE_STRING, char* SUB_STRING, const unsigned long STARTING_INDEX, const unsigned long TO_TAKE);

void STRING_COPY(char* DESTINATION, const char* STRING);

void STRING_SET(char* STRING, const char* SET);

void STRING_REPLACE_CHAR(char* STRING, const char FIND_CHAR, const char REPLACE_CHAR);

void STRING_REMOVE_FIRST(char* STRING);

void STRING_REMOVE_LAST(char* STRING);

int STRING_REMOVE_INDEX(char* STRING, unsigned long INDEX);

void STRING_REMOVE_CHAR(char* STRING, const char CHAR);

void STRING_TRIM(char* STRING);

void STRING_CLEAR(char* STRING);

int STRING_FORMAT(char* STRING, const char* FORMAT, ...);


//
// [/EDIT]




// [CONDITIONS]
//
int STRING_EQUALS(const char* STRING, const char* COMPARER);

int STRING_IS_EMPTY(const char* STRING);

int STRING_CONTAINS_CHAR(const char* STRING, const char CHAR);

int STRING_STARTS_WITH(const char* STRING, const char* STARTING);

int STRING_ENDS_WITH(const char* STRING, const char* ENDING);

int STRING_IS_INT(const char* STRING);


//
// [/CONDITIONS]




// [PROPERTIES]
//


/**
 * BRIEF  : RETURNS HOW MANY CHARS ARE IN THE GIVEN STRING
 *
 * USAGE  : int LENGTH = STRING_LENGTH("ABCDEF");
*/
unsigned long STRING_LENGTH(const char *STRING);


/**
 * BRIEF  : RETURNS HOW MANY BYTES USED BY THE STRING
 *
 * NOTE   : A STRING'S SIZE IS LENGTH + 1 (IF ASCII)
 *
 * USAGE  : int SIZE = STRING_SIZE("ABCDEF");
*/
unsigned long STRING_SIZE(const char* STRING);


//
// [/PROPERTIES]




#endif
